# Arrays

In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\shiva\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.0               |   py38haa95532_0         2.9 MB
    ------------------------------------------------------------
                                           Total:         2.9 MB

The following packages will be UPDATED:

  conda                                        4.8.3-py38_0 --> 4.10.0-py38haa95532_0




conda-4.10.0         | 2.9 MB    |            |   0% 
conda-4.10.0         | 2.9 MB    |            |   1% 
conda-4.10.0         | 2.9 MB    | #2         |  13% 
conda-4.10.0         | 2.9 MB    | ##9        |  29% 
conda-4.10.0         | 2.9 MB    | #####3     |  54% 
conda-4.10.0         | 2.9 MB    | #######8   |  79% 
conda-4.10.0         | 2.9 MB    | #########9 |  99% 
c

In [2]:
import numpy as np

In [3]:
my_lst=[1,2,3,4]

In [4]:
arr= np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr


array([1, 2, 3, 4])

In [9]:
arr.shape

(4,)

In [22]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[34,5,6,3,3]

arr=np.array([lst1,lst2,lst3])

In [12]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [34,  5,  6,  3,  3]])

In [14]:
arr.shape

(3, 5)

In [17]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 3,  4,  5],
       [ 6, 34,  5],
       [ 6,  3,  3]])

In [18]:
arr.shape

(3, 5)

# Indexing


In [19]:
arr= np.array([1,2,3,4,5,6,7,8,9])

In [20]:
arr[3]

4

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[34,5,6,3,3]

arr=np.array([lst1,lst2,lst3])

In [24]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [34,  5,  6,  3,  3]])

In [32]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [35]:
arr[1:,3:]

array([[5, 6],
       [3, 3]])

In [36]:
arr[1:,2:4]

array([[4, 5],
       [6, 3]])

In [38]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [42]:
arr=np.arange(0,11,step=2)

In [43]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
arr=np.array([1,2,3,4,5,6,7,78])
arr

array([ 1,  2,  3,  4,  5,  6,  7, 78])

In [49]:
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100])

In [51]:
arr1=arr
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100])

In [54]:
arr1[3:]=500
arr1
arr

array([  1,   2,   3, 500, 500, 500, 500, 500])

In [55]:
arr1= arr.copy()

In [59]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000]


In [64]:
val=2
print(arr<2)
arr*val
arr[arr<2]

[ True False False False False False False False]


array([1])

In [67]:
val=2
arr[arr<200]

array([1, 2, 3])

In [68]:
np.ones(4)

array([1., 1., 1., 1.])

In [69]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
np.random.rand(3,3)

array([[0.2815761 , 0.71414404, 0.33241235],
       [0.95239467, 0.67550853, 0.60156227],
       [0.28666689, 0.99169428, 0.41939522]])

In [72]:
arr_exp=np.random.randn(4,4)

In [73]:
arr_exp


array([[-0.16356923,  0.49345656,  1.03046258, -0.48761663],
       [-0.68214714, -2.12826445,  1.41309915,  0.44406255],
       [ 0.36335312,  1.72964899, -1.09650862,  0.87054523],
       [-0.12215246, -0.32773471,  0.33405218,  1.2141551 ]])

In [76]:
conda install seaborn

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [84]:
np.random.randint(0,100,8).reshape(2,4)

array([[56, 77, 30, 46],
       [58, 97, 48, 81]])

In [86]:
np.random.random_sample((1,5))

array([[0.28170273, 0.92577836, 0.38524871, 0.9469631 , 0.45584763]])